<!-- _source/haml/includes/html-test.inc -->

			<h1>Level 1 heading</h1>
			<h2>Level 2 heading</h2>
			<p>P Sed scelerisque sagittis lorem. Phasellus sodales. Nulla urna justo, vehicula in, suscipit nec, molestie sed, tellus. Quisque justo. Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Etiam viverra augue non enim.</p>
			
			<h3>Level 03 Heading</h3>
			<p>P Sed scelerisque sagittis lorem. Phasellus sodales. Nulla urna justo, vehicula in, suscipit nec, molestie sed, tellus. Quisque justo. Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Etiam viverra augue non enim.</p>
			
			<h4>Level 04 Heading</h4>
			<p>P Sed scelerisque sagittis lorem. Phasellus sodales. Nulla urna justo, vehicula in, suscipit nec, molestie sed, tellus. Quisque justo. Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Etiam viverra augue non enim.</p>
			
			<h5>Level 05 Heading</h5>
			<p>P Sed scelerisque sagittis lorem. Phasellus sodales. Nulla urna justo, vehicula in, suscipit nec, molestie sed, tellus. Quisque justo. Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Etiam viverra augue non enim.</p>
			
			<h6>Level 06 Heading</h6>
			<p>P Sed scelerisque sagittis lorem. Phasellus sodales. Nulla urna justo, vehicula in, suscipit nec, molestie sed, tellus. Quisque justo. Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Etiam viverra augue non enim.</p>
			
			<blockquote>
				<p>P Paragraph inside Blockquote: Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Sed scelerisque sagittis lorem.</p>
				<p>P Paragraph inside Blockquote: Nam libero leo, elementum in, dapibus a, suscipit vitae, purus. Duis arcu. Integer dignissim fermentum enim. Morbi convallis felis vel nibh. Sed scelerisque sagittis lorem.</p>
			</blockquote>
			
			<address>Address: Example address 224, Sweden</address>
			
			<pre><strong>Preformated:</strong>Testing one row
	and another</pre>
			
			<p>
				I am <a href="?abc123">the a tag</a> example<br />
				I am <a href="#" class="arrow">the a.arrow</a> example<br />
				
				I am <abbr title="test of ABBR">the abbr tag</abbr> example<br />
				
				I am <acronym title="test of ACRONYM">the acronym tag</acronym> example<br />
				I am <b>the b tag</b> example<br />
				I am <big>the big tag</big> example<br />
				
				I am <cite>the cite tag</cite> example<br />
				
				I am <code>the code tag</code> example<br />
				I am <del>the del tag</del> example<br />
				I am <dfn>the dfn tag</dfn> example<br />
				
				I am <em>the em tag</em> example<br />
				
				I am <font face="verdana">the font tag</font> example<br />
				I am <i>the i tag</i> example<br />
				I am <ins>the ins tag</ins> example<br />
				
				I am <kbd>the kbd tag</kbd> example<br />
				
				I am <q>the q tag <q>inside</q> a q tag</q> example<br />
				I am <s>the s tag</s> example<br />
				I am <samp>the samp tag</samp> example<br />
				
				I am <small>the small tag</small> example<br />
				I am <span>the span tag</span> example<br />
				I am <strike>the strike tag</strike> example<br />
				I am <strong>the strong tag</strong> example<br />
				
				I am <sub>the sub tag</sub> example<br />
				I am <sup>the sup tag</sup> example<br />
				I am <tt>the tt tag</tt> example<br />
				I am <var>the var tag</var> example<br />
				
				I am <u>the u tag</u> example
			</p>
			
			<hr />
			
			<ul>
				<li>Unordered list 01 Unordered list 01 Unordered list 01 Unordered list 01 Unordered list 01 Unordered list 01</li>
				<li>Unordered list 02</li>
				<li>Unordered list 03
					<ul>
			
						<li>Unordered list inside list level 2</li>
			
						<li>Unordered list inside list level 2
							<ul>
								<li>Unordered list inside list level 3</li>
								<li>Unordered list inside list level 3</li>
							</ul>
						</li>
			
					</ul>
				</li>
			</ul>

			<ul class="arrow" >
				<li><strong>UL.ARROW</strong> 1 Unordered list 01 Unordered list 01 Unordered list 01 Unordered list 01 Unordered list 01</li>
				<li>Unordered list 02</li>
				<li>Unordered list 03
					<ul>
			
						<li>Unordered list inside list level 2</li>
			
						<li>Unordered list inside list level 2
							<ul>
								<li>Unordered list inside list level 3</li>
								<li>Unordered list inside list level 3</li>
							</ul>
						</li>
			
					</ul>
				</li>
			</ul>
			<ul class="divided" >
				<li><strong>UL.DIVIDED</strong> Item number one</li>
				<li>Item number two</li>
				<li>Item number three</li>
			</ul>
			<ul class="arrow divided" >
				<li><strong>UL.ARROW.DIVIDED</strong> Item number one</li>
				<li>Item number two</li>
				<li>Item number three</li>
			</ul>

			<ol>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 03
					<ol>
						<li>Ordered list inside list level 2</li>
			
						<li>Ordered list inside list level 2
							<ol>
			
								<li>Ordered list inside list level 3</li>
								<li>Ordered list inside list level 3</li>
							</ol>
						</li>
					</ol>
				</li>
			 <li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
		<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
				<li>Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01 Ordered list 01</li>
				<li>Ordered list 02</li>
			</ol>
			
			<dl class="clearfix">
				<dt>Description list title 01</dt>
				<dd>Description list description 01</dd>
				<dt>Description list title 02</dt>
				<dd>Description list description 02</dd>
				<dd>Description list description 03</dd>
			</dl>
			<h3>Table</h3>
			<table>
				<caption>Table Caption</caption>
				<tr>
					<th>Table head th</th>
					<th>Table head th</th>
					<th>Table head th</th>
					<th>Table head th</th>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
			</table>
			<h3>Table.zebra</h3>
			<table class="zebra">
				<caption>Table Caption</caption>
				<tr>
					<th>Table head th</th>
					<th>Table head th</th>
					<th>Table head th</th>
					<th>Table head th</th>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
				<tr>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
					<td>Table body td</td>
				</tr>
			</table>

	
			<form action="#">
				<fieldset>
					<legend>Form legend</legend>
					<div class="field">
						<label for="f1">Text input:</label>
						<input type="text" id="f1" value="input text" />
					</div>
					<div class="field">
						<label for="f2">Radio input:</label>
						<input type="radio" id="f2" />
					</div>
					<div class="field">
						<label for="f3">Checkbox input:</label>
						<input type="checkbox" id="f3" />
					</div>
					<div class="field">
						<label for="f4">Select field:</label>
						<select id="f4">
							<option>Option 01</option>
							<option>Option 02</option>
						</select>
					</div>
					<div class="field">
						<label for="f5">Textarea:</label>
						<textarea id="f5" cols="30" rows="5">Textarea text</textarea>
					</div>
					<div class="field">
						<label for="f6">Button:</label>
						<button class="button" id="f6" type="button">BUTTON.button</button>
						<input class="button" type="submit" value="INPUT.button" />
					</div>
				</fieldset>
			</form>
<hr />
<form action="#" method="get" name="exampleForm" id="exampleForm">
  <fieldset>
    <p>
      <label for="ex1">Label for this field</label><br />
      <select name="ex1" id="ex1"><option value="1">Select an Option</option></select>
    </p>
    <p>
      <label for="ex2">Label for this field</label><br />
      <select name="ex2" id="ex2"><option value="1">Select an Option</option></select>
    </p>
    <p>
      <label for="ex3">Label for this field</label><br />
      <select name="ex3" id="ex3"><option value="1">Select an Option</option></select>
    </p>
    <p>
      <label for="ex4">Output to Excel</label>
      <input type="checkbox" name="ex4" id="ex4" />
    </p>
    <p>
      <button class="blueButton" type="submit">Generate Report</button>
      &nbsp;
      <button type="reset">Reset</button>
    </p>
  </fieldset>
</form>
<hr />
<p><input type="image" class="goButton" src="/_res/img/x.gif" /></p>
<p>
  <button class="button">BUTTON.button</button>&nbsp;
  <a href="#" class="button">A.button</a>&nbsp;
  <a href="#" class="button smallButton">A.button.smallButton</a>
</p>
<p class="clearfix">.blueButton<br />
  <button class="blueButton">BUTTON.blueButton</button>&nbsp;
  <input type="submit" value="INPUT.blueButton" class="blueButton" />&nbsp;
  <a href="#" class="blueButton">A.blueButton</a>
</p>
<p class="clearfix">.darkButton<br />
  <button class="darkButton">BUTTON.darkButton</button>&nbsp;
  <input type="submit" value="INPUT.darkButton" class="darkButton" />&nbsp;
  <a href="#" class="darkButton">A.darkButton</a>
</p>
<p class="clearfix">.lightButton<br />
  <button class="lightButton">BUTTON.lightButton</button>&nbsp;
  <input type="submit" value="INPUT.lightButton" class="lightButton" />&nbsp;
  <a href="#" class="lightButton">A.lightButton</a>
</p>
<!-- END _source/haml/includes/html-test.inc -->